<?php
/** @var \peteleco\movie\block\view $block */
$movie = $block->getMovie();

?>
<link href="https://unpkg.com/tailwindcss@1.4.6/dist/tailwind.min.css" rel="stylesheet">

<div class="container">
    <div class="md:flex">
        <div class="md:w-1/3 md:pr-12">
            <img  class="w-full"
                  src="<?php echo $this->helper(\Peteleco\Movie\Helper\Data::class)->getFullPosterPath($movie->getPosterPath()); ?>"
                  alt="<?php echo $movie->getTitle();?>">
            <?php if(!$block->wasAddToFavoriteList()):?>
            <a
                href="<?php echo $block->getUrl('movie/movie/addToFavorite') . 'id/' . $movie->getId(); ?>"
                class="block mt-4 w-full bg-gray-400 py-2 px-4 rounded text-center">Add to favorite list</a>
            <?php else: ?>
                <a
                    href="<?php echo $block->getUrl('movie/movie/removeFromFavorite') . 'id/' . $movie->getId(); ?>"
                    class="block mt-4 w-full bg-red-400 text-white hover:text-white hover:no-underline hover:bg-red-500 py-2 px-4 rounded text-center">Remove from favorite list</a>
            <?php endif;?>
        </div>
        <div class="md:w-2/3">
            <h1 class="text-6xl"><?php echo $movie->getTitle();?></h1>
            <div class="bg-white px-4 py-2 rounded"><?php echo $movie->getOverview();?></div>
        </div>
    </div>
</div>

