<!-- Header Import Button -->
<?php echo $this->getChildHtml('LimaMovie_Search_ImportButton'); ?>

<div class="admin__data-grid-header">
	<!-- Filter Tab -->
    <?php echo $this->getChildHtml('LimaMovie_Search_Filter'); ?>
	<!-- Pagination -->
    <?php echo $this->getChildHtml('LimaMovie_Search_Pagination'); ?>
</div>

<!-- Grid Results -->
<?php echo $this->getChildHtml('LimaMovie_Search_Grid'); ?>
