<?php use Peteleco\Movie\Helper\Data;

/** @var Magento\Backend\Block\Template $block */

$requestToken = $this->helper(Data::class)->getConfig('movie/general/api_token');
?>
<link type="text/css" href="https://unpkg.com/tailwindcss@1.4.6/dist/tailwind.min.css" rel="stylesheet">


<!-- With Tailwind Style -->
<div class="w-full bg-gray-200">
    <div class="w-full">
        <div class="relative px-2 py-2 flex">
            <input id="txt_search" name="txt_search" class="bg-purple-white shadow rounded border-0 p-3 w-full mr-2"
                   maxlength="40" placeholder="<?= __('Search by movie title...'); ?>"/>

            <button id="pick-movie" class="bg-gray-500 hover:bg-gray-300 text-white font-bold py-2 px-4 rounded shadow">
                <span><?= __('Search!'); ?></span>
            </button>


        </div>
    </div>
    <div class="flex flex-wrap" id="searchResult">
        <!-- Movie -->
    </div>

    <!--    <div class="flex flex-col items-center my-12">-->
    <!--        <div class="flex text-gray-700">-->
    <!--            <div class="h-8 w-8 mr-1 flex justify-center items-center  cursor-pointer">-->
    <!--                <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">-->
    <!--                    <polyline points="15 18 9 12 15 6"></polyline>-->
    <!--                </svg>-->
    <!--            </div>-->
    <!--            <div class="flex h-8 font-medium ">-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-transparent">1</div>-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-orange-600  ">2</div>-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-transparent">3</div>-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-transparent">...</div>-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-transparent">13</div>-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-transparent">14</div>-->
    <!--                <div class="w-8 md:flex justify-center items-center  cursor-pointer leading-5 transition duration-150 ease-in  border-t-2 border-transparent">15</div>-->
    <!--                <div class="w-8 h-8  flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in border-t-2 border-orange-600">2</div>-->
    <!--            </div>-->
    <!--            <div class="h-8 w-8 ml-1 flex justify-center items-center  cursor-pointer">-->
    <!--                <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right w-4 h-4">-->
    <!--                    <polyline points="9 18 15 12 9 6"></polyline>-->
    <!--                </svg>-->
    <!--            </div>-->
    <!--        </div>-->
    <!--    </div>-->


    <script>
        require([
            'jquery',
        ], function ($) {

            $(document).ready(function () {

                $('#txt_search').keyup(function (e) {
                    if (e.keyCode == 13) {
                        searchMovieTMDB();
                    }
                });
                $("#pick-movie").bind("click", searchMovieTMDB);

                function searchMovieTMDB() {
                    var search = $("#txt_search").val();
                    var movieUrlApi = 'https://api.themoviedb.org/4';
                    var movieUrlApiToken = 'Bearer <?= $requestToken;?>';
                    var searchUrl = '/search/movie';
                    var movieUrlQuery = new URL(movieUrlApi + searchUrl);
                    var movieApiHeaders = new Headers();
                    movieApiHeaders.append('Authorization', movieUrlApiToken);
                    if (search !== "" && search.length >= 3) {
                        // If was typed more than 3 letters
                        movieUrlQuery.searchParams.append('query', search);

                        fetch(movieUrlQuery.href, {
                                method: 'GET',
                                headers: movieApiHeaders,
                                mode: 'cors',
                                cache: 'default'
                            }
                        ).then(function (response) {
                            return response.json().then(function (jsonResponse) {
                                var len = jsonResponse['results'].length;
                                $("#searchResult").empty();
                                for (var i = 0; i < len; i++) {
                                    $("#searchResult").append(movieBlock(jsonResponse['results'][i]['id'], jsonResponse['results'][i]['title'], jsonResponse['results'][i]['overview'], jsonResponse['results'][i]['poster_path'],false));
                                }
                                // binding click event to li
                                $("#searchResult  .movie-item").bind("click", function () {
                                    setMovie(this);
                                });
                            })
                        });

                        function setMovie(el) {
                            var movie = {
                                id: $(el).attr('data-id'),
                                title: $(el).attr('data-title'),
                                overview: $(el).attr('data-overview'),
                                poster_path: $(el).attr('data-poster_path'),
                            };
                            $('input[name="general[tmdb_id]"]').val($(el).attr('data-id')).change();
                            $('input[name="general[title]"]').val($(el).attr('data-title')).change();
                            $('[name="general[overview]"]').val($(el).attr('data-overview')).change();
                            $('[name="general[poster_path]"]').val($(el).attr('data-poster-path')).change();
                            $(el).toggleClass('bg-green-300');

                            // // hide other movies
                            $("#searchResult .movie-item").each(function(index, el){
                                if($(el).attr('data-id') != movie.id) {
                                    $(el).removeClass('bg-green-300');
                                }
                            });
                        }

                        function movieBlock(movieId, title, overview, posterPath, picked) {
                            var movieAttr = "data-id='" + movieId + "' data-title='" + title + "' data-overview='" + overview + "' data-poster-path='" + posterPath + "' ";
                            var moviePoster = "https://image.tmdb.org/t/p/w200/" + posterPath;
                            var classMovie = (picked) ? 'bg-green-200' : '';
                            var movieBlock = '<div ' + movieAttr + '  class="movie-item mb-2 w-1/2 p-2 cursor-pointer '+classMovie+'" >';
                            movieBlock += '<div class="bg-white w-full p-2 flex">';
                            movieBlock += '<div class="relative w-32">';
                            movieBlock += '<img src="' + moviePoster + '" class="w-full" alt="' + title + '">';
                            movieBlock += '</div>';
                            movieBlock += '<div class="w-full bg-white px-2 py-2 h-14">';
                            movieBlock += '<span class="text-2xl justify-start border-b-4 pb-1 border-yellow-500">' + title + '</span>';
                            movieBlock += '</div>';
                            movieBlock += '</div>';
                            movieBlock += '</div>';
                            return movieBlock;
                        }

                        // $.ajax({
                        //     url: movieUrlQuery.href,
                        //     type: 'GET',
                        //     header: { Authorization: movieUrlApiToken},
                        //     data: {query:search},
                        //     dataType: 'json',
                        //     success:function(response){
                        //
                        //
                        //
                        //     }
                        // });
                    }

                }

                // $('#pick-movie').click(function(){
                //     alert('teste');
                //     $('input[name="tmdb[tmdb_id]"]').val('123123').change();
                // });
            });
        });
    </script>
