<div class="page-main-actions">
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="<?php echo __('Import Movies'); ?>">
            <div class="page-actions-buttons">
                <div id="import-movies" title="<?php echo __('Import Movies'); ?>" class="actions-split">
                    <button id="import-movies-button" title="<?php echo __('Import Movies'); ?>" class="primary" data-ui-id="import-movies-button">
                        <span><?php echo __('Import Movies'); ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
