<div id="redirect-url" data-redirect-url="<?php /* @escapeNotVerified */ echo $this->getUrl('movie/queue/index') ?>"></div>
<div id="endpoint-search-result" data-endpoint-search-result="<?php /* @escapeNotVerified */ echo $this->getUrl('movie/search/result') ?>"></div>
<div id="endpoint-movie-search-import" data-endpoint-movie-search-import="<?php /* @escapeNotVerified */ echo $this->getUrl('movie/search/import') ?>"></div>
